# Generated by Django 5.0.6 on 2024-07-12 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=70)),
                ('telefono', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('region', models.CharField(choices=[('Arica y Parinacota', 'Arica y Parinacota'), ('Tarapacá', 'Tarapacá'), ('Antofagasta', 'Antofagasta'), ('Atacama', 'Atacama'), ('Coquimbo', 'Coquimbo'), ('Valparaíso', 'Valparaíso'), ('Metropolitana de Santiago', 'Metropolitana de Santiago'), ('Libertador General Bernardo O’Higgins', 'Libertador General Bernardo O’Higgins'), ('Maule', 'Maule'), ('Ñuble', 'Ñuble'), ('Biobío', 'Biobío'), ('La Araucanía', 'La Araucanía'), ('Los Ríos', 'Los Ríos'), ('Los Lagos', 'Los Lagos'), ('Aysén del General Carlos Ibáñez del Campo', 'Aysén del General Carlos Ibáñez del Campo'), ('Magallanes y la Antártica Chilena', 'Magallanes y la Antártica Chilena')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
