# Generated by Django 5.0.6 on 2024-07-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterBIKE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('product_image', models.ImageField(upload_to='imgProductos')),
            ],
        ),
    ]
