# Generated by Django 5.0.6 on 2024-07-15 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterBIKE', '0004_product_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('orderred_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Aceptado', 'Aceptado'), ('En camino', 'En camino'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterBIKE.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterBIKE.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
